"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Scene, SceneBundle, VisualStrategy } from "@/types/project";

export function ScenesPanel({projectId,onProjectChanged}:{projectId:number;onProjectChanged:()=>void}) {
  const [bundle,setBundle]=useState<SceneBundle|null>(null);
  const [state,setState]=useState<"loading"|"idle"|"planning"|"review"|"failed">("loading");
  const [error,setError]=useState("");
  async function load(){const data=await api.getScenes(projectId);setBundle(data);setState(data.scenes.length?"review":"idle");}
  useEffect(()=>{let active=true;api.getScenes(projectId).then(data=>{if(!active)return;setBundle(data);setState(data.scenes.length?"review":"idle");}).catch(e=>{if(!active)return;setError(e.message);setState("failed");});return()=>{active=false};},[projectId]);
  async function generate(){if(bundle?.scenes.length&&!confirm("Regenerate the full scene plan? Existing scene edits will be replaced."))return;setState("planning");setError("");try{setBundle(await api.generateScenes(projectId));setState("review");onProjectChanged();}catch(e){setError(e instanceof Error?e.message:"Scene planning failed");setState("failed");onProjectChanged();}}
  async function save(scene:Scene){const value=(id:string)=>(document.getElementById(id) as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement).value;await api.updateScene(scene.id,{narration_text:value(`narration-${scene.id}`),target_duration:Number(value(`duration-${scene.id}`)),visual_description:value(`visual-${scene.id}`),shot_type:value(`shot-${scene.id}`),camera_motion:value(`motion-${scene.id}`),visual_strategy:value(`strategy-${scene.id}`) as VisualStrategy});await load();}
  async function duplicate(scene:Scene){await api.createScene(projectId,{order:scene.order+1,narration_text:scene.narration_text,target_duration:scene.target_duration,species:scene.species,environment:scene.environment,animal_behavior:scene.animal_behavior,visual_description:scene.visual_description,shot_type:scene.shot_type,camera_motion:scene.camera_motion,visual_strategy:scene.visual_strategy});await load();}
  async function add(){const base=bundle?.scenes.at(-1);if(!base){setError("Generate a scene plan before adding a manual scene.");return;}await api.createScene(projectId,{order:base.order+1,narration_text:"Manual narration bridge.",target_duration:5,species:base.species,environment:base.environment,animal_behavior:"Behavior to review",visual_description:"Manual visual description",shot_type:"wide",camera_motion:"static observation",visual_strategy:"STOCK_VIDEO"});await load();}
  async function remove(scene:Scene){if(!confirm(`Delete scene ${scene.order}?`))return;await api.deleteScene(scene.id);await load();}
  async function regenerate(scene:Scene){await api.regenerateScene(scene.id);await load();}
  async function move(scene:Scene,direction:-1|1){if(!bundle)return;const ids=bundle.scenes.map(item=>item.id);const index=ids.indexOf(scene.id);const next=index+direction;if(next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];setBundle(await api.reorderScenes(projectId,ids));}
  const mismatch=Math.abs(bundle?.duration_difference??0)>15;
  return <section className="research-section"><div className="section-heading"><div><div className="eyebrow">Phase 3</div><h2>Visual scene plan</h2><p>Timed narration scenes with varied shots and recommended visual strategies.</p></div><div className="actions"><button className="button secondary" disabled={!bundle?.scenes.length} onClick={add}>+ Add scene</button><button className="button" disabled={state==="planning"} onClick={generate}>{state==="planning"?"Planning…":bundle?.scenes.length?"Regenerate full plan":"Generate scenes"}</button></div></div>
    {error&&<div className="error">{error}</div>}{state==="idle"&&<div className="empty"><h2>No scenes yet</h2><p>Approve a script, then generate an editable timed visual plan.</p></div>}
    {bundle&&bundle.scenes.length>0&&<><div className={`duration-bar ${mismatch?"mismatch":""}`}><span><strong>{Math.round(bundle.total_duration)} sec</strong> scene plan</span><span>Target {Math.round(bundle.target_duration)} sec</span><span>Difference {bundle.duration_difference>0?"+":""}{Math.round(bundle.duration_difference)} sec</span></div>{mismatch&&<div className="warning">Scene duration differs materially from the requested project duration. Review the approved script length or scene timing.</div>}
      <div className="scene-list">{bundle.scenes.map(scene=>{const latest=scene.prompts.at(-1);return <article className="card scene-card" key={scene.id}><div className="scene-index"><strong>{scene.order}</strong><button onClick={()=>move(scene,-1)} aria-label="Move scene up">↑</button><button onClick={()=>move(scene,1)} aria-label="Move scene down">↓</button></div><div className="scene-content"><div className="scene-meta"><span>{scene.start_time.toFixed(1)}–{scene.end_time.toFixed(1)} sec</span><span className="pill">{scene.visual_strategy.replaceAll("_"," ")}</span><span>{scene.shot_type} · {scene.camera_motion}</span></div><label>Narration<textarea id={`narration-${scene.id}`} defaultValue={scene.narration_text} rows={4}/></label><div className="scene-fields"><label>Duration<input id={`duration-${scene.id}`} type="number" min="1" max="120" step="0.5" defaultValue={scene.target_duration}/></label><label>Strategy<select id={`strategy-${scene.id}`} defaultValue={scene.visual_strategy}><option value="STOCK_VIDEO">Stock video</option><option value="AI_IMAGE_MOTION">AI image motion</option><option value="AI_VIDEO">AI video</option></select></label><label>Shot<input id={`shot-${scene.id}`} defaultValue={scene.shot_type}/></label><label>Camera<input id={`motion-${scene.id}`} defaultValue={scene.camera_motion}/></label></div><label>Visual description<textarea id={`visual-${scene.id}`} defaultValue={scene.visual_description} rows={3}/></label>{latest&&<details><summary>Generation prompts · v{latest.version}</summary><p><strong>Image:</strong> {latest.image_prompt}</p><p><strong>Video:</strong> {latest.video_prompt}</p></details>}<div className="actions"><button className="text-button" onClick={()=>save(scene)}>Save</button><button className="text-button" onClick={()=>regenerate(scene)}>Regenerate visual plan</button><button className="text-button" onClick={()=>duplicate(scene)}>Duplicate</button><button className="text-button danger-text" onClick={()=>remove(scene)}>Delete</button></div></div></article>})}</div></>}
  </section>;
}
