from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select, update
from sqlalchemy.orm import Session, selectinload

from app.core.config import get_settings
from app.db.session import get_db
from app.models.project import Project
from app.models.script import Script, ScriptSection
from app.schemas.script import (
    ScriptBundle,
    ScriptRead,
    ScriptSectionRead,
    ScriptSectionUpdate,
    ScriptUpdate,
    SectionRegenerateRequest,
)
from app.services.llm import (
    ScriptOrchestrator,
    estimate_duration_seconds,
    target_word_range,
)

router = APIRouter(tags=["scripts"])
DatabaseSession = Annotated[Session, Depends(get_db)]


def script_or_404(script_id: int, db: Session) -> Script:
    script = db.scalar(
        select(Script)
        .where(Script.id == script_id)
        .options(selectinload(Script.sections), selectinload(Script.project))
    )
    if script is None:
        raise HTTPException(status_code=404, detail="Script not found")
    return script


def section_or_404(section_id: int, db: Session) -> ScriptSection:
    section = db.scalar(
        select(ScriptSection)
        .where(ScriptSection.id == section_id)
        .options(
            selectinload(ScriptSection.script).selectinload(Script.sections),
            selectinload(ScriptSection.script).selectinload(Script.project),
        )
    )
    if section is None:
        raise HTTPException(status_code=404, detail="Script section not found")
    return section


def build_bundle(project: Project, db: Session) -> ScriptBundle:
    versions = list(
        db.scalars(
            select(Script)
            .where(Script.project_id == project.id)
            .options(selectinload(Script.sections))
            .order_by(Script.version.desc())
        )
    )
    settings = get_settings()
    minimum, maximum = target_word_range(
        project.requested_duration_seconds,
        settings.narration_words_per_minute,
        settings.script_length_tolerance,
    )
    is_mock = settings.llm_provider.lower() == "mock"
    return ScriptBundle(
        project_id=project.id,
        status="review" if versions else "idle",
        provider=settings.llm_provider,
        is_mock=is_mock,
        target_word_min=minimum,
        target_word_max=maximum,
        current=versions[0] if versions else None,
        versions=versions,
        warning=(
            "Development narration generated by the mock LLM; review it before approval."
            if is_mock and versions
            else None
        ),
    )


@router.post("/api/projects/{project_id}/script/generate", response_model=ScriptBundle)
async def generate_script(project_id: int, db: DatabaseSession) -> ScriptBundle:
    project = db.get(Project, project_id)
    if project is None:
        raise HTTPException(status_code=404, detail="Project not found")
    try:
        await ScriptOrchestrator().generate(project, db)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"LLM provider failed: {exc}") from exc
    return build_bundle(project, db)


@router.get("/api/projects/{project_id}/script", response_model=ScriptBundle)
def get_script(project_id: int, db: DatabaseSession) -> ScriptBundle:
    project = db.get(Project, project_id)
    if project is None:
        raise HTTPException(status_code=404, detail="Project not found")
    return build_bundle(project, db)


@router.patch("/api/scripts/{script_id}", response_model=ScriptRead)
def update_script(script_id: int, payload: ScriptUpdate, db: DatabaseSession) -> Script:
    script = script_or_404(script_id, db)
    changes = payload.model_dump(exclude_unset=True)
    if "full_text" in changes:
        paragraphs = [part.strip() for part in changes["full_text"].split("\n\n") if part.strip()]
        if len(paragraphs) != len(script.sections):
            raise HTTPException(
                status_code=422,
                detail="Full script edits must preserve one paragraph per traceable section",
            )
        for section, paragraph in zip(script.sections, paragraphs, strict=True):
            section.text = paragraph
        settings = get_settings()
        for section in script.sections:
            section.estimated_duration_seconds = estimate_duration_seconds(
                section.text, settings.narration_words_per_minute
            )
        ScriptOrchestrator.recalculate_script(script)
    if "tone" in changes:
        script.tone = changes["tone"]
    script.approved = False
    db.commit()
    db.refresh(script)
    return script


@router.patch("/api/script-sections/{section_id}", response_model=ScriptSectionRead)
def update_section(
    section_id: int, payload: ScriptSectionUpdate, db: DatabaseSession
) -> ScriptSection:
    section = section_or_404(section_id, db)
    for key, value in payload.model_dump(exclude_unset=True).items():
        setattr(section, key, value.strip())
    section.script.approved = False
    ScriptOrchestrator.recalculate_script(section.script)
    db.commit()
    db.refresh(section)
    return section


@router.post("/api/script-sections/{section_id}/regenerate", response_model=ScriptSectionRead)
async def regenerate_section(
    section_id: int, payload: SectionRegenerateRequest, db: DatabaseSession
) -> ScriptSection:
    section = section_or_404(section_id, db)
    try:
        section.script.approved = False
        return await ScriptOrchestrator().regenerate_section(section, payload.mode, db)
    except Exception as exc:
        db.rollback()
        raise HTTPException(status_code=502, detail=f"LLM provider failed: {exc}") from exc


@router.post("/api/scripts/{script_id}/approve", response_model=ScriptRead)
def approve_script(script_id: int, db: DatabaseSession) -> Script:
    script = script_or_404(script_id, db)
    db.execute(
        update(Script)
        .where(Script.project_id == script.project_id, Script.id != script.id)
        .values(approved=False)
    )
    script.approved = True
    db.commit()
    db.refresh(script)
    return script
